### ISSUE TITLE
Initial Task List

### ISSUE THREAD

**Issue by lawrenceleejr** [mdurk/ScatteringRadiation#1]
Transferring over from https://github.com/kpachal/ScatteringRadiation/issues/1

Task list:

- [x] Matthew gets a GitHub account and posts it here.
- [x] Forks this repository and makes KP and LL collaborators (and then we move the remaining tasks into issues on his fork)
- [x] Joins UTK/CMS slack - https://join.slack.com/t/utkcms/shared_invite/zt-11zrt57tf-V4dSOQ3ZBALW~cC85pfWgw
- [x] Gets ROOT installed on his Fedora machine (https://root.cern/install/#fedora)
- [x] Install Docker desktop (https://docs.docker.com/engine/install/fedora/)
- [ ] Learn the basics of ROOT (https://root.cern.ch/root/htmldoc/guides/primer/ROOTPrimer.html)
- [x] Learn Linux basics (https://utk.instructure.com/courses/144571/assignments/1133871)
- [x] Learn git basics (https://utk.instructure.com/courses/144571/assignments/1133872)
- [ ] Lower priority: Start getting familiar with GEANT (https://www.youtube.com/watch?v=Lxb4WZyKeCE&list=PLLybgCU6QCGWgzNYOV0SKen9vqg4KXeVL)

Background material:
* https://arxiv.org/abs/1412.4717
* https://arxiv.org/pdf/1504.01527.pdf
* Technical design report for ARIEL location: https://www.dropbox.com/s/od509bi41sx20kk/DarkLight_at_ARIEL_TDR-3.pdf?dl=0
